### ISSUE TITLE
Ports should be identified automatically

### ISSUE THREAD

**Issue by schemar** [OpenST/mosaic-chains#11]
## Story
As a user
I want mosaic to identify free ports automatically
Because I am too lazy to check the used ports and add the appropriate options to run it

## Scenario
Given that mosaic containers are running
When I start a new container
Then it automatically uses a free port for docker port publishing on the host

## Info
We could get the currently published `mosaic_*` container ports from `docker ps` or similar and skip those when starting new containers.

**Comment by benjaminbollen** [comment]
closing in favor of #53
