### ISSUE TITLE
linkAuxiliaryChain

### ISSUE THREAD

**Issue by benjaminbollen** [OpenST/mosaic-chains#17]
note: (re)move/use chainSetup from mosaic.js to mosaic-chains
- this ticket is more narrow in scope than "chainSetup", so name function "linkAuxiliaryChain"
- rewrite in typescrypt
- gets as input origin connection and aux connection
- gets as input OST contract on origin
- gets as input OST' contract on aux (not yet initialised) - has its own organization contract
- gets as input owner addresses for organization deployment for gateway on origin/aux

do:
- deploy org's for anchors
- deploy anchors
- deploy org's of gateways against these anchors
- deploy, activate gateway for OST'

**Comment by schemar** [comment]
Integrated in #19.

Creating an auxiliary chain without linking it or vice-versa doesn't make sense in my opinion.

@benjaminbollen please re-open if you disagree.
