### ISSUE TITLE
Init auxiliary chain

### ISSUE THREAD

**Issue by schemar** [OpenST/mosaic-chains#19]
0 
- deploy on origin:
  - anchor (height: 0, SR: 0) - note improve possibly later with actual state root after geth init 
  - OST gateway
  - do initial stake for OST with HashLock

1
- generate validator address in geth
- generate deployer address in zeroProvider
- add generated address to genesis and allocate `0x295be96e640669720000000`
- add to genesis Clique validators to extraData
- geth init
- at 0 gas:
  - deploy OST prime
  - deploy anchor with StateRoot of origin, after initial stake was declared
  - move 0x295be96e640669720000000 into OST'
  - do initial stake and mint from funded to beneficiary on aux
  - raise gas price; (~add more block sealers~)
- write config + bootnode(s)

note: https://github.com/ostdotcom/saas-api/blob/master/README-AUX-SETUP.md

⚠️ This should replace the existing `./build.sh` script.

**Comment by benjaminbollen** [comment]
- generate validator address in geth
- generate deployer address in zeroProvider
- add generated address to genesis and allocate `0x295be96e640669720000000`
- add to genesis Clique validators to extraData
- geth init

**Comment by schemar** [comment]
@benjaminbollen and I had a discussion on account management for the deployment of the required contracts in order to initialize a new chain.
We decided to use unlocked accounts on the chain nodes for now. We don't want account management inside mosaic-chains and you are running these nodes with mosaic-chains anyways. So you may as well manage the accounts there.

Later, Ledger, Trezor, and other options should be made available.

#25 adds support for `--unlock` and `--password` to mosaic-chains.

**Comment by schemar** [comment]
@benjaminbollen what about setting things like the organization owner/admin or the bounty? Should the user provide that on the command line when invoking `./mosaic new` or should we assume sane defaults with optional options to the CLI or what do you think is a good way?

I cannot find a satisfying answer.

**Comment by schemar** [comment]
@benjaminbollen and I decided that we should use a per-chain config in a sub-directory that contains an example file. The concrete configs would be `.gitignore`d, the example not.

I implemented the config part, with an `InitConfig` as described above. I also started work on a `MosaicConfig` that can be shared after the auxiliary chain is up and running.

I finished deployment of contracts on auxiliary and am halfway through generating the addresses for the auxiliary chain (sealer and deployer). The addresses are generated and stored in `keystore`, but they are not yet accessible to mosaic-chains.

We agreed that it would be ok for now to use a password file for the geth accounts, as they should only be temporary anyways and proper sealers should be added after initialization is done.

Next up:

1. reading the generated addresses
2. generating the genesis file
3. `geth init`ializing auxiliary
4. deploying the relevant auxiliary contracts
5. moving tokens into OST prime
6. stake and mint from origin
7. raise gas price

Open TODOs:

- [ ] add password file path to CLI
- [ ] add mosaic path to CLI
- [ ] documentation
- [ ] readme

**Comment by schemar** [comment]
- [ ] reading the generated addresses
- [ ] generating the genesis file
- [ ] geth initializing auxiliary
- [ ] deploying the relevant auxiliary contracts
- [ ] moving tokens into OST prime
- [ ] stake and mint from origin
- [ ] raise gas price

Open TODOs:

- [ ] add password file path to CLI
- [ ] add mosaic path to CLI
- [ ] documentation
- [ ] readme

**Comment by schemar** [comment]
- [ ] staking on origin
- [ ] moving tokens into OST prime
- [ ] mint on auxiliary
- [ ] raise gas price

Open TODOs:

- [ ] use actual expected co-gateway address to activate gateway
- [ ] anchor on origin gets actual state root from auxiliary
- [ ] anchor on auxiliary gets actual state roots from origin
- [ ] add password file path to CLI
- [ ] add mosaic path to CLI
- [ ] tests
- [ ] documentation
- [ ] readme
- [ ] use separate organizations for anchor and gateway

**Comment by schemar** [comment]
Required for PR:

- [ ] anchor on origin gets actual state root from auxiliary
- [ ] anchor on auxiliary gets actual state roots from origin
- [ ] mint on auxiliary
- [ ] raise gas price
- [ ] create utility chain subdirectory *with initial `chain_data` from after `init`*
- [ ] store mosaic config in utility chain subdirectory
- [ ] documentation
- [ ] readme

Stretch goal (or follow-up tickets):

- [ ] add password file path to CLI
- [ ] add mosaic path to CLI
- [ ] tests
- [ ] at the very start, fail if the chain directory already exists
- [ ] at the very start, fail if a container with the chain name already exists
- [ ] `try`/`catch` all `await`s
- [ ] replace `string` with `BN` where applicable
- [ ] no implicit `any`

**Comment by benjaminbollen** [comment]
commencing review... 🤓
