### ISSUE TITLE
New auxiliary chain should be verified

### ISSUE THREAD

**Issue by schemar** [OpenST/mosaic-chains#20]
### Description

Document how to verify a newly created chain and all deployed contracts, possibly get help from Bala.

### Proposal

**Pre-requisites**

- Origin chain should be up and running.
- Auxiliary chain should be up and running.

**Command**
```
./mosaic verify-chain origin-websocket auxiliary-websocket originChainIdentifier auxChaiIdentifier
```

_origin-websocket_: origin chain endpoint. Needed for fetching contract state variables for verification.
_auxiliary-websocket_: Auxiliary chain endpoint. Needed for fetching contract state variables for verification.  
_originChainIdentifier_: Origin chain identifier
_auxChaiIdentifier_: Auxiliary chain identifier

**Contracts BIN Verification**

- Verify that deployed contracts BIN are correct. Read the BIN of contracts from mosaic.js and validate it with deployed contracts BIN using web3.eth.getCode method. This includes library bytecode verifications also.
https://github.com/OpenST/mosaic.js/blob/develop/index.js#L50
https://web3js.readthedocs.io/en/1.0/web3-eth.html#eth-code

**Origin EIP20Gateway Contract Verification Steps**
   - Gateway should be activated.
   - organization address stored in Gateway contract should match MosaicConfig ostGatewayOrganizationAddress.
   - remoteGateway address should match MosaicConfig ostEIP20CogatewayAddress.
   - stateRootProvider should match origin anchorAddress. 
   - valueToken address should match simpleTokenAddress from MosaicConfig.
   - baseToken address should match simpleTokenAddress from MosaicConfig.
   
**Origin Anchor Contract Verification Steps**
  - coAnchor address should match with aux chain anchorAddress.
  - organization address stored in anchor contract should match MosaicConfig anchorOrganizationAddress.
  - remoteChainId should match auxiliary chain id from MosaicConfig.

**OSTPrime Contract verification Steps**
  - Initialized value should be TRUE.
  - OSTPrime organization address should match MosaicConfig ostCoGatewayOrganizationAddress.
  - coGateway address stored should match MosaicConfig ostEIP20CogatewayAddress.
  - valueToken address should match simpleTokenAddress from MosaicConfig.

**Auxiliary Anchor Contract Verification Steps**
  - coAnchor address should be origin chain anchorAddress.
  - organization address stored in anchor contract should match MosaicConfig anchor organization address.
  - remoteChainId should match origin chain id of MosaicConfig.

**Auxiliary CoGateway Contract Verification Steps**
   - Read CoGateway organization address from MosaicConfig and validate it with organization address stored in CoGateway contract.
   - remoteGateway address should match origin chain ostEIP20GatewayAddress.
   - utilityToken should match OSTPrime contract address.
   - CoGateway valueToken address should match Gateway ValueToken address.
   - stateRootProvider should match origin chain anchorAddress. 
   - valueToken address should match simpleTokenAddress address from MosaicConfig.

Updating MosaicConfig format as per issue #44 for reference
```
{
    "originChain": {
        "contractAddresses": {
            "gatewayLibAddress": "0x226630773315aF4d01F0492D5CDfc3Be0BA98Ff5",
            "messageBusAddress": "0x5f3341EA5989aD3129E325027b8d908b63709A00",
            "merklePatriciaLibAddress": "0xB4D7f6747CEFbDcA11bDDd92a16134dc95B0DD9B"
            "simpleTokenAddress": "0x5f3341EA5989aD3129E325027b8d908b63709A00",
        },
        "chain": "12346"
    },
    "auxiliaryChains": {
        "301": {
            "contractAddresses": {
                "origin": {
                    "anchorOrganizationAddress": "0x850212e53c1d8898740dd776E78C77B87D94F234",
                    "anchorAddress": "0xaa52E47eB094423117435234877383792c95AED1",
                    "ostGatewayOrganizationAddress": "0x15152AaDcA3C571B0Ba332e1020FCeA43F95A3F9",
                    "ostEIP20GatewayAddress": "0x799C12667e5E4E94E4710EA1Ea7809fEb46Cbc87"
                },
                "auxiliary": {
                    "anchorOrganizationAddress": "0x5d1d4c61688EF305b794aAAF4d01EC51Adb0FfF0",
                    "anchorAddress": "0xd7A26a0A13AD2219617C0e4f101EBD99a2d7386A",
                    "ostCoGatewayOrganizationAddress": "0xC710C5A2100D73B55bA008A864B380E68b74a943",
                    "ostPrimeAddress": "0xF8D6cEA623537c91ba5AA153b8be76784b9d7788",
                    "ostEIP20CogatewayAddress": "0xf7E06851206040dE9b252Eb5377869830f61D105"
                }
            }
     }
```

**Comment by schemar** [comment]
This ticket is somewhat blocked by #44 I think. For the verification, addresses should probably be read from the stored configuration. What do you think @deepesh-kn ?

**Comment by schemar** [comment]
This ticket requires a mosaic config, right? Is there a ticket for that?
/cc @deepesh-kn

**Comment by abhayks1** [comment]
Please find proposal in the ticket description.
It's available for review 🚀 🎸

**Comment by abhayks1** [comment]
Testing in progress..
