### ISSUE TITLE
Reset the admin after creating a new chain

### ISSUE THREAD

**Issue by schemar** [OpenST/mosaic-chains#32]
When running `mosaic new`, we have to set the admin of the two organizations to be equal to the keys we use for deployment, because we have to activate the gateway and set the co-gateway on OST prime.

However, we can set these two admin addresses to `address(0)` once we are done with deployment.

**Comment by abhayks1** [comment]
> When running `mosaic new`, we have to set the admin of the two organizations to be equal to the keys we use for deployment.

@schemar here two organizations are Gateway organization and anchor organization on origin chain. Similarly for aux chain. Right?

**Comment by schemar** [comment]
> > When running `mosaic new`, we have to set the admin of the two organizations to be equal to the keys we use for deployment.
> 
> @schemar here two organizations are Gateway organization and anchor organization on origin chain. Similarly for aux chain. Right?

Check the code. Some of the organizations are already set to specified admins. Others are set to the deployment accounts. Only reset the ones that use the deployment accounts.
