### ISSUE TITLE
when multiple chains start they should use different p2p ports

### ISSUE THREAD

**Issue by benjaminbollen** [OpenST/mosaic-chains#42]
The chain nodes should run on the same port as the port that is published on the host. Otherwise, their port does not match the port that the host's IP requires to reach the node.

Whenever a node is started, then the port (e.g. `30303`) of that node should equal the `port` of the node description.

Plausible bug: while the networkId should help prevent accidently connecting to the wrong bootnodes. however, I got wrong block segments when restarting multiple chains.  Suspected problem is that they share the 30303 port?

**Comment by schemar** [comment]
If you start multiple chains, subsequent chains' containers publish increasing port numbers on the host (`30304`, etc.). However, the node *inside the container* always runs on port `30303`.
Only the first node's container has port `30303` published on the host.
If nodes announce themselves somewhere with their port, than multiple ports would announce themselves from the host machine with the same port `30303`, which the host would then forward to the *first* container (and subsequently *only the first node* that was started).

If this is the case, then the (easy) fix would be to start the nodes inside the containers on increasing ports identical to the ones published on the host. Furthermore, the `--port` option should apply to the published port **and** the node's port inside the container.

**Comment by benjaminbollen** [comment]
yes, that is likely a better analysis :)

**Comment by schemar** [comment]
See also https://wiki.parity.io/Configuring-Parity-Ethereum
