### ISSUE TITLE
Design mosaic config

### ISSUE THREAD

**Issue by schemar** [OpenST/mosaic-chains#44]
Mosaic configurations store data about mosaic chains: chain ids, contract addresses, etc.
The mosaic chains repository handles mosaic configs and writes the first mosaic config of a newly created auxiliary chain.

The layout of the mosaic configuration must be thought out well. It will be distributed to others to run and connect to mosaic chains.

:warning: Updating the code in mosaic chains should be a *separate* follow-up ticket.

ℹ️ Keep in mind that this configuration should later be registered in a smart contract on-chain.

### Context
This is a **research issue** to find out what the configuration should look like.

**Background:**
Mosaic chains configurations should be separate from OpenST (or BrandedToken) configurations. Generally, they should be separate files and OpenST (and BrandedToken) should *reference* the Mosaic config where applicable.

**This ticket is *only* about the mosaic config and *not* about any other configs like OpenST.**

**Comment by schemar** [comment]
Think of multiple solutions and explain which ones you were thinking of and why you chose the chosen one.

Possibly think about maps in solidity to have an extendable on-chain configuration.

**Comment by sarvesh-ost** [comment]
While designing config, the following use cases are considered. 

1. As a mosaic user, I want to know all the auxiliary chain for a given origin chain.

    **Solution:**  
  - [X] Config should list all the auxiliary chains.

2. As a mosaic user, I want to connect to any given auxiliary chain so that I can see available contracts/dapps. 

    **Solution:**
 - [X] Config should provide details to connect to an existing auxiliary chain like boot nodes and genesis file.

3. As a mosaic user, I want to covert ERC20 ost to auxiliary base coin so that I can pay for transaction gas fee in the auxiliary chain. 

    **Solution:** 
- [X] Config should list ost gateway related contract addresses to enable ost stake and mint. 
- [ ] Config should also provide a mechanism like known hashLock(or any other solution) so that facilitator can progress stake message on behalf of staker. 

**Details**
* Below JSON represents a mosaic config based on the above requirement. 
* JSON only represents meta-data of mosaic config hence the value of many fields in the JSON is left as blank which should be replaced with appropriate value. 
* Proposed config captures details of the single origin chain and it's multiple auxiliary chains. 
* `ostStakeConfig`(can be named better) is currently a place holder for the information needed by the staker to perform first ost stake in order to mint base coins. This part requires more discussion. 

```
{
  "originChain": {
    "chainId": 3,
    "contractAddresses": {
      "simpleTokenAddress": "",
      "anchorOrganizationAddress": "",
      "anchorAddress": "",
      "merklePatriciaLibAddress": "",
      "GatewayLibAddress": "",
      "messageBusAddress": "",
      "ostGatewayOrganizationAddress": "",
      "ostEIP20GatewayAddress": ""
    }
  },
  "auxiliaryChains": [
    {
      "chainId": 1406,
      "bootNodes": [],
      "genesis": {},
      "contractAddresses": {
        "ostPrimeAddress": "",
        "anchorOrganizationAddress": "",
        "anchorAddress": "",
        "merklePatriciaLibAddress": "",
        "GatewayLibAddress": "",
        "messageBusAddress": "",
        "ostCoGatewayOrganizationAddress": "",
        "ostEIP20CogatewayAddress": ""
      }
    },
    {
      "chainId": 1407,
      "bootNodes": [],
      "genesis": {},
      "contractAddresses": {
        "ostPrimeAddress": "",
        "anchorOrganizationAddress": "",
        "anchorAddress": "",
        "merklePatriciaLibAddress": "",
        "GatewayLibAddress": "",
        "messageBusAddress": "",
        "ostCoGatewayOrganizationAddress": "",
        "ostEIP20CogatewayAddress": ""
      }
    }
  ],
  "ostStakeConfig": {}
}
```

**Comment by sarvesh-ost** [comment]
**Proposal 2** 

Slightly different from proposal 1.
 Instead of listing the aux chain as an array, all the side chains can be represented as an object where each key of the object represents `chainId` against which aux details are kept. 
```
{
  "originChain": {
    "chainId": 3,
    "contractAddresses": {
      "simpleTokenAddress": "",
      "anchorOrganizationAddress": "",
      "anchorAddress": "",
      "merklePatriciaLibAddress": "",
      "GatewayLibAddress": "",
      "messageBusAddress": "",
      "ostGatewayOrganizationAddress": "",
      "ostEIP20GatewayAddress": ""
    }
  },
  "auxiliaryChains": {
    "1406": {
      "chainId": 1406,
      "bootNodes": [],
      "genesis": {},
      "contractAddresses": {
        "ostPrimeAddress": "",
        "anchorOrganizationAddress": "",
        "anchorAddress": "",
        "merklePatriciaLibAddress": "",
        "GatewayLibAddress": "",
        "messageBusAddress": "",
        "ostCoGatewayOrganizationAddress": "",
        "ostEIP20CogatewayAddress": ""
      },
      "ostStakeConfig": {}
    },
    "1407": {
      "chainId": 1407,
      "bootNodes": [],
      "genesis": {},
      "contractAddresses": {
        "ostPrimeAddress": "",
        "anchorOrganizationAddress": "",
        "anchorAddress": "",
        "merklePatriciaLibAddress": "",
        "GatewayLibAddress": "",
        "messageBusAddress": "",
        "ostCoGatewayOrganizationAddress": "",
        "ostEIP20CogatewayAddress": ""
      },
      "ostStakeConfig": {}
    }
  }
}
```

**Comment by schemar** [comment]
Nice thoughts! 🙌 
Somme comments:

>     1. As a mosaic user, I want to know all the auxiliary chain for a given origin chain.
>        **Proposed solution:**

Is this really true for mosaic users or would this be more appropriate for validators, market makers, and the likes. Anyways I think this is valuable information 👍 

>     * [x]  Config should provide details to connect to an existing auxiliary chain like boot nodes and genesis file.

Should we really add the genesis to the config? We could, it doesn't have to be human readable 🤔 The bootnodes definitely help and don't need to go in a separate file 👍 

>     * `ostStakeConfig`(can be named better) is currently a place holder for the information needed by the staker to perform first ost stake in order to mint base coins. This part requires more discussion.

Yeah, this is an important, difficult part...

JSON comments:

> ```json
> {
>   "originChain": {
>     "chainId": 3,
>     "contractAddresses": {
>       "simpleTokenAddress": "",
>       "anchorOrganizationAddress": "",
>       "anchorAddress": "",
>       "merklePatriciaLibAddress": "",
>       "GatewayLibAddress": "",
>       "messageBusAddress": "",
>       "ostGatewayOrganizationAddress": "",
>       "ostEIP20GatewayAddress": ""
>     }
>   },
>```

Anchor, its organization, gateway libraries, and the OST gateway address would be different per auxiliary chain on the same origin chain. These fields should probably move to the auxiliary part 🤔 

>```json
>   "auxiliaryChains": [
>     {
>       "chainId": 1406,
>       "bootNodes": [],
>       "genesis": {},
>       "contractAddresses": {
>         "ostPrimeAddress": "",
>         "anchorOrganizationAddress": "",
>         "anchorAddress": "",
>         "merklePatriciaLibAddress": "",
>         "GatewayLibAddress": "",
>         "messageBusAddress": "",
>         "ostCoGatewayOrganizationAddress": "",
>         "ostEIP20CogatewayAddress": ""
>       },
>       "ostStakeConfig": {}
>     },
>```

* `bootnodes` should probably be a string how it is used by geth and parity (comma-separated). But I am not sure here 🧐

> **Proposal 2**
> Instead of listing the aux chain as an array, all the side chains can be represented as an object where each key of the object represents `chainId` against which aux details are kept.

I like this proposal, because I can access a chain config for a known chain id without iterating over all auxiliary chains to find the one with my id.

**Comment by sarvesh-ost** [comment]
```
Is this really true for mosaic users or would this be more appropriate for validators, market makers, and the likes. Anyways I think this is valuable information 👍
```
I will update the description, thanks 👍 

```
Should we really add the genesis to the config? We could, it doesn't have to be human readable 🤔 The bootnodes definitely help and don't need to go in a separate file 👍
```
We could keep genesis into a separate file. What is a good way of referencing genesis file into mosaic-config? As we know, it requires both bootnode and genesis to connect to a node. 

```
Anchor, its organization, gateway libraries, and the OST gateway address would be different per auxiliary chain on the same origin chain. These fields should probably move to the auxiliary part 🤔
```
True 👍 

```
bootnodes should probably be a string how it is used by geth and parity (comma-separated). But I am not sure here 🧐

```
There can be more than 1 boot nodes that we may want to publish. 🤔

**Comment by sarvesh-ost** [comment]
### **Draft 2**


**Proposal 1** 
```
{
  "originChain": {
    "chainId": 3,
    "contractAddresses": {
      "simpleTokenAddress": "",
      "merklePatriciaLibAddress": "",
      "GatewayLibAddress": "",
      "messageBusAddress": ""
    }
  },
  "auxiliaryChains": [
    {
      "chainId": 1406,
      "bootNodes": [],
      "genesis": {},
      "contractAddresses": {
        "origin": {
          "anchorOrganizationAddress": "",
          "anchorAddress": "",
          "ostGatewayOrganizationAddress": "",
          "ostEIP20GatewayAddress": ""
        },
        "auxiliary": {
          "ostPrimeAddress": "",
          "anchorOrganizationAddress": "",
          "anchorAddress": "",
          "merklePatriciaLibAddress": "",
          "GatewayLibAddress": "",
          "messageBusAddress": "",
          "ostCoGatewayOrganizationAddress": "",
          "ostEIP20CogatewayAddress": ""
        }
      },
      "ostStakeConfig": {}
    },
    {
      "chainId": 1407,
      "bootNodes": [],
      "genesis": {},
      "contractAddresses": {
        "origin": {
          "anchorOrganizationAddress": "",
          "anchorAddress": "",
          "ostGatewayOrganizationAddress": "",
          "ostEIP20GatewayAddress": ""
        },
        "auxiliary": {
          "ostPrimeAddress": "",
          "anchorOrganizationAddress": "",
          "anchorAddress": "",
          "merklePatriciaLibAddress": "",
          "GatewayLibAddress": "",
          "messageBusAddress": "",
          "ostCoGatewayOrganizationAddress": "",
          "ostEIP20CogatewayAddress": ""
        }
      },
      "ostStakeConfig": {}
    }
  ]
} 
```

**Proposal 2** 

```
{
  "originChain": {
    "chainId": 3,
    "contractAddresses": {
      "simpleTokenAddress": "",
      "merklePatriciaLibAddress": "",
      "GatewayLibAddress": "",
      "messageBusAddress": ""
    }
  },
  "auxiliaryChains": {
    "1406": {
      "chainId": 1406,
      "bootNodes": [],
      "genesis": {},
      "contractAddresses": {
        "origin": {
          "anchorOrganizationAddress": "",
          "anchorAddress": "",
          "ostGatewayOrganizationAddress": "",
          "ostEIP20GatewayAddress": ""
        },
        "auxiliary": {
          "ostPrimeAddress": "",
          "anchorOrganizationAddress": "",
          "anchorAddress": "",
          "merklePatriciaLibAddress": "",
          "GatewayLibAddress": "",
          "messageBusAddress": "",
          "ostCoGatewayOrganizationAddress": "",
          "ostEIP20CogatewayAddress": ""
        }
      },
      "ostStakeConfig": {}
    },
    "1407": {
      "chainId": 1407,
      "bootNodes": [],
      "genesis": {},
      "contractAddresses": {
        "origin": {
          "anchorOrganizationAddress": "",
          "anchorAddress": "",
          "ostGatewayOrganizationAddress": "",
          "ostEIP20GatewayAddress": ""
        },
        "auxiliary": {
          "ostPrimeAddress": "",
          "anchorOrganizationAddress": "",
          "anchorAddress": "",
          "merklePatriciaLibAddress": "",
          "GatewayLibAddress": "",
          "messageBusAddress": "",
          "ostCoGatewayOrganizationAddress": "",
          "ostEIP20CogatewayAddress": ""
        }
      },
      "ostStakeConfig": {}
    }
  }
}
```

**Comment by schemar** [comment]
>> bootnodes should probably be a string how it is used by geth and parity (comma-separated). But I am not sure here 🧐
>
> There can be more than 1 boot nodes that we may want to publish. 🤔

Right, it would be a comma-separated list of bootnodes.

**Comment by schemar** [comment]
Nice 🐨 

> ### Draft 2
> **Proposal 2**
> 
> ```json
> {
>   "originChain": {
>     "chainId": 3,
>     "contractAddresses": {
>       "simpleTokenAddress": "",
>       "merklePatriciaLibAddress": "",
>       "GatewayLibAddress": "",
>       "messageBusAddress": ""
>     }
>   },
>```

LGTM 👍 

> ```json
>   "auxiliaryChains": {
>     "1406": {
>       "chainId": 1406,
> ```

Do we need to repeat this here? We could for convenience, however it could also lead to potential mismatches/errors...

> ```json
>       "bootNodes": [],
> ```

Maybe a string (see above).

> ```json
>       "genesis": {},
>       "contractAddresses": {
>         "origin": {
>           "anchorOrganizationAddress": "",
>           "anchorAddress": "",
>           "ostGatewayOrganizationAddress": "",
>           "ostEIP20GatewayAddress": ""
>         },
>         "auxiliary": {
>           "ostPrimeAddress": "",
>           "anchorOrganizationAddress": "",
>           "anchorAddress": "",
>           "merklePatriciaLibAddress": "",
>           "GatewayLibAddress": "",
>           "messageBusAddress": "",
>           "ostCoGatewayOrganizationAddress": "",
>           "ostEIP20CogatewayAddress": ""
>         }
>       },
> ```

Addresses LGTM 👍 

> ```json
>       "ostStakeConfig": {}
> ```

Ideas so far?

> ```json
>     },
>   }
> }
> ```

**Comment by schemar** [comment]
Maybe it helps to have a look at the ZeppelinOS configuration files as well: https://docs.zeppelinos.org/docs/configuration.html

**Comment by sarvesh-ost** [comment]
> Nice 🐨
> 
> > ### Draft 2
> > **Proposal 2**
> > ```json
> > {
> >   "originChain": {
> >     "chainId": 3,
> >     "contractAddresses": {
> >       "simpleTokenAddress": "",
> >       "merklePatriciaLibAddress": "",
> >       "GatewayLibAddress": "",
> >       "messageBusAddress": ""
> >     }
> >   },
> > ```
> 
> LGTM 👍
> 
> > ```json
> >   "auxiliaryChains": {
> >     "1406": {
> >       "chainId": 1406,
> > ```
> 
> Do we need to repeat this here? We could for convenience, however it could also lead to potential mismatches/errors...

Sure, we can remove it 👍 
> 
> > ```json
> >       "bootNodes": [],
> > ```
> 
> Maybe a string (see above).

For a good JSON structure , collection should be represented as array instead of string,  right? 
Your suggestion for the string because that's how geth expects it? 

> 
> > ```json
> >       "genesis": {},
> >       "contractAddresses": {
> >         "origin": {
> >           "anchorOrganizationAddress": "",
> >           "anchorAddress": "",
> >           "ostGatewayOrganizationAddress": "",
> >           "ostEIP20GatewayAddress": ""
> >         },
> >         "auxiliary": {
> >           "ostPrimeAddress": "",
> >           "anchorOrganizationAddress": "",
> >           "anchorAddress": "",
> >           "merklePatriciaLibAddress": "",
> >           "GatewayLibAddress": "",
> >           "messageBusAddress": "",
> >           "ostCoGatewayOrganizationAddress": "",
> >           "ostEIP20CogatewayAddress": ""
> >         }
> >       },
> > ```
> 
> Addresses LGTM 👍
> 
> > ```json
> >       "ostStakeConfig": {}
> > ```
> 
> Ideas so far?
1. I thought about known hashlock approach.

Unlock secret will be known after first stake and mint. Any bad actor can use this to steal bounty or reward for any next stake and mint.

2. Contract similar to gateway composer can be one of the solutions Where stakers performs request stake and facilitator(selected  random or round Robin fashion) accepts it by providing a hashlock.

> 
> > ```json
> >     },
> >   }
> > }
> > ```

**Comment by schemar** [comment]
See also new https://github.com/OpenST/facilitator/issues/1 which could be the first consumer of this!

> > > ```json
> > >       "bootNodes": [],
> > > ```
> > 
> > 
> > Maybe a string (see above).
> 
> For a good JSON structure , collection should be represented as array instead of string, right?
> Your suggestion for the string because that's how geth expects it?

Yes, you are right 👍 Can be transformed when needed, depending on the context.

> > > ```json
> > >       "ostStakeConfig": {}
> > > ```
> > 
> > 
> > Ideas so far?
> 
> 1. I thought about known hashlock approach.
> Unlock secret will be known after first stake and mint. Any bad actor can use this to steal bounty or reward for any next stake and mint.

True for the "free facilitation". However, reward would be zero. So the bad actor would only steal the bounty, but do all the work. I can't tell right now if this is a real problem. How high do we expect the bounties to be in practice? Higher than the cost of facilitation?

> 2. Contract similar to gateway composer can be one of the solutions Where stakers performs request stake and facilitator(selected  random or round Robin fashion) accepts it by providing a hashlock.

True, can you please add your thoughts to https://github.com/OpenST/facilitator/issues/1 so we can discuss there? I think it's out-of-scope for this ticket *how the facilitation* will be done. Maybe an abstract config that allows for all scenarios would be providing an address where to stake to and an optional hash lock secret (optional in the config)? 🤔 

On another note, do you know [JSON Schema]? We should probably define the config in JSON Schema. What do you think?

[json schema]: https://json-schema.org/

**Comment by sarvesh-ost** [comment]
Yes, make sense 👍

**Comment by schemar** [comment]
I was wrong about the zero reward. @benjaminbollen noted that the initial stake should also carry a reward.

**Comment by sarvesh-ost** [comment]
@benjaminbollen  Did you get chance to look into this?

**Comment by deepesh-kn** [comment]
Draft 2, Proposal 2 looks fine to go ahead.

Few comments:
- Document about the `originChain`->`contractAddresses` and `auxiliaryChains`->`chain_id`->`originChain`->`contractAddresses`
- Document more about `ostStakeConfig`. How it can be used for staking
- Since this config can be registered in smart contract, we can keep the genesis in the config `"genesis": {}`.
- Defining the config in JSON Schema looks nice to go forward.

**Comment by sarvesh-ost** [comment]
Based on all the discussion, here is the final version.  

```
{
  "originChain": {
    "chainId": 3,
    "contractAddresses": { // Contracts deployed on origin chain, should be reused for all auxiliary chains. 
      "simpleTokenAddress": "",
      "merklePatriciaLibAddress": "",
      "GatewayLibAddress": "",
      "messageBusAddress": ""
    }
  },
  "auxiliaryChains": {
    "1406": {
      "chainId": 1406,
      "bootNodes": [], //List of boot nodes
      "genesis": {}, 
      "contractAddresses": { // Contract addresses specific to single auxiliary chain 
        "origin": { // Contracts deployed on origin chain specific to single auxiliary chain
          "anchorOrganizationAddress": "",
          "anchorAddress": "",
          "ostGatewayOrganizationAddress": "",
          "ostEIP20GatewayAddress": "",
          "ostComposerAddress": "" 
        },
        "auxiliary": { // Contracts deployed on the auxiliary chain
          "ostPrimeAddress": "",
          "anchorOrganizationAddress": "",
          "anchorAddress": "",
          "merklePatriciaLibAddress": "",
          "GatewayLibAddress": "",
          "messageBusAddress": "",
          "ostCoGatewayOrganizationAddress": "",
          "ostEIP20CogatewayAddress": ""
        }
      }
    },
    "1407": {
      "chainId": 1407,
      "bootNodes": [], //List of boot nodes
      "genesis": {},
      "contractAddresses": { // Contract addresses specific to single auxiliary chain 
        "origin": { // Contracts deployed on origin chain specific to single auxiliary chain
          "anchorOrganizationAddress": "",
          "anchorAddress": "",
          "ostGatewayOrganizationAddress": "",
          "ostEIP20GatewayAddress": "",
          "ostComposerAddress": ""
        },
        "auxiliary": { // Contracts deployed on the auxiliary chain
          "ostPrimeAddress": "",
          "anchorOrganizationAddress": "",
          "anchorAddress": "",
          "merklePatriciaLibAddress": "",
          "GatewayLibAddress": "",
          "messageBusAddress": "",
          "ostCoGatewayOrganizationAddress": "",
          "ostEIP20CogatewayAddress": ""
        }
      }
    }
  }
}
```

**Comment by schemar** [comment]
Good. Did we discuss where/how to store the config? We need one config per origin chain in this model. Or we support multiple origin chains in a single config.

**Comment by deepesh-kn** [comment]
> Good. Did we discuss where/how to store the config? 

We can keep this config in the repository for now. It can be exposed in NPM package.

>We need one config per origin chain in this model. Or we support multiple origin chains in a single config.

Single config per origin chain.

**Comment by schemar** [comment]
> > Good. Did we discuss where/how to store the config?
> 
> We can keep this config in the repository for now. It can be exposed in NPM package.

Yes, but *where?* Or is that up to the implementer?

> > We need one config per origin chain in this model. Or we support multiple origin chains in a single config.
> 
> Single config per origin chain.

Just to be sure: one config *per origin* and **not** a *single* config for all chains. Right?

**Comment by schemar** [comment]
Also regarding the where: how is it named? Basically: how to access based on knowing the origin?

**Comment by sarvesh-ost** [comment]
I also feel it can be exposed via npm package. Then it will matter less how we keep in the repository. Maybe a folder named `mosaic-config` where there will be JSON based on chain name/id like `ropsten.json` or `kovan.json`. It more up to the implementor, in my opinion. 

I roughly imagine it being exposed like this but implementer can also come up with better design if needed. 
```
const mosaicChain = require('@openst/mosaic-chains')
const ropostenMosaicConfig = mosaicChain.config.ropsten;
const mainnetMosaicConfig = mosaicChain.config.mainnet;
```

What do you think?

**Comment by deepesh-kn** [comment]
> Yes, but where? Or is that up to the implementer?

We can discuss this on call. I am not sure if I have understood your question correctly.
In mosaic-chain repo, in config folder may be. The implementer can decide.

> Just to be sure: one config per origin and not a single config for all chains. Right?

Yes, one config per origin.

> Also regarding the where: how is it named? Basically: how to access based on knowing the origin?

@schemar,  how you are imagining this? @sarvesh-ost has commented above, what do you think?

**Comment by schemar** [comment]
LGTM 🐺
