### ISSUE TITLE
Non-conflicting, deterministic default ports per chain

### ISSUE THREAD

**Issue by schemar** [OpenST/mosaic-chains#53]
## Story
As a user
I want chains' ports to be non-conflicting by default
Because setting all the options per chain is tedious.

## Scenario
Given that I stopped any one of many running chains
When I start that chain again
Then, by default, the ports do not conflict with any of the currently running chains.

## Info
The current behavior always starts at the same "base" ports when you run `./mosaic` and counts up from there. If it tries to use a port that is blocked by another application, then docker returns an error and the chain does not actually start.

This means the following. If you:
1. start more than one chain
2. then stop for example the second chain from the start command
3. then try to start the stopped chain again without specifying any ports

Then it would fail. Mosaic would try to use ports that are already occupied by the first chain from the original start command.

If instead the port would depend on the chain id, the same chain would by default always use the same port and you could stop and start them in any order. The port of a specific chain would by default never change. It would also simplify port forwarding from other machines to the machine where mosaic is running.

### Suggestion
This is a suggested solution, please discuss other/better solutions below.
By default, a chain uses the following ports:
* port: `3<chain-id>`
* rpc: `4<chain-id>`
* ws: `5<chain-id>`

Where `<chain-id>` would always be exactly four characters, with leading zeros in case of a shorter chain id.

Examples:

| Chain | Port | RPC | WS |
| ---| --- | --- | --- |
| `3` | `30003` | `40003` | `50003` |
| `200` | `30200` | `40200` | `50200` |
| `1406` | `31406` | `41406` | `51406` |

Obvious issue: would not work with chain IDs that have more than 4 digits. An alternative could be random ports in a spcified range, which are fixed per chain (RNG seeded with chain id). It would be less "human readable" to understand which port belongs to which chain.

:warning: This would probably replace #11 :warning:

**Comment by schemar** [comment]
What's the final way to set the ports?

**Comment by benjaminbollen** [comment]
the simplest, seemingly sufficient proposal is

```
X_PORT + ChainId
```
without mod; for the near future this should resolve all issues, and it's clear enough understood this not a protocol specification - just to help.

**Comment by schemar** [comment]
ℹ️ Note:

1. For the p2p port, run the node inside the container with the same port that is published to the host.
2. In order to clarify behavior of the `--port` option, only allow to start a single chain with every run of `./mosaic`.
