### ISSUE TITLE
Mosaic chains should be publishable

### ISSUE THREAD

**Issue by schemar** [OpenST/mosaic-chains#54]
Publish mosaic chains on NPM JS.

Create an index file to export the services that are used directly by the commands so that consumers could write their own commands.

`tsconfig.json` must include (in addition to anything that might be there already):
* `"declaration": true` to add the declaration files to the output (to be used by anyone using TypeScript who depends on mosaic chains).
* `"target": "es5"` to be backwards compatible.
* `"outDir": "./lib"` to be in line with `mosaic.js`.

`package.json` must include (in addition):
* `"main": "./lib/index.js"`
* `"bin": {"mosaic": "<file-path>"}` with a file path to the mosaic.js that is the output of the build process
* `"files"` to include only the necessary files in the published package (probably only from within `lib`? See also `mosaic.js` to compare)
* `"scripts":`
    * A `package` script which compiles the necessary code with typescript
    * A `prepack' script which runs any necessary steps before publishing like installing dependencies, building, etc.

Verify that the package can be imported by a TypeScript project as expected by packaging it locally and installing it in a test project.
Verify that you can at least:
1. use the `bin` (e.g. start a chain)
2. use the library (e.g. start a chain)
3. have type definitions available

**Comment by benjaminbollen** [comment]
what is being published? is mosaic chains usable as a lib?

Is this package then usable to run integration tests?

What is the version number of mosaic chains currently ? 0.1.0; should we increment the minor number currently for each publishing act, as we it s still in a build-up phase?

**Comment by schemar** [comment]
No version number currently, as there is no release planned.

I would publish it in both forms. As a lib so others can use it to write code that handles mosaic chains. And as a binary so other projects can run chains, for example for integration tests.

**Comment by benjaminbollen** [comment]
In my opinion the publishing as a library is less important. good for learning though

**Comment by schemar** [comment]
Using the lib could also be a valid approach to use it in integration tests 🤔

**Comment by schemar** [comment]
The published package also requires the chains' configurations in order to be able to start chains.

**Comment by schemar** [comment]
The published package should include and expose the mosaic config (if available).

**Comment by schemar** [comment]
Test the packaging (get inspired by openst-contract)
