### ISSUE TITLE
Improve types

### ISSUE THREAD

**Issue by schemar** [OpenST/mosaic-chains#58]
Create type aliases for common types and use them in the project.
Check if you can use existing type aliases from web3.

Types to create:

* `type Address = string;`

**Comment by benjaminbollen** [comment]
valid, but are there more types? 

a Bytes20 for an Address is out of reach, probably?

**Comment by schemar** [comment]
Web3js expects a string as far as I know :(

**Comment by benjaminbollen** [comment]
should be improved when touching code
