### ISSUE TITLE
Gas price should be configurable for initial sealer

### ISSUE THREAD

**Issue by schemar** [OpenST/mosaic-chains#60]
## Story

As a user
I want to configure the initial gas price of a new auxiliary chain
Because I don't want transactions to be free
(And I don't *expect* transactions to be free)

## Scenarios

Given that I run the command to create a new auxiliary chain
When the command finishes
Then a sealer runs
And the gas price is the one configured in the init config

## Info

* It should be a new mandatory field in the initialization configuration.
* At the end of the current initialization process, the sealer should be stopped and restarted with the configured gas price.
* The warning output to update the gas price should be removed.

**Comment by benjaminbollen** [comment]
This initial sealer needs to allow other sealers to join, and in most situations just get voted out after the handover.  Also the RPC should be used to set the gasprice later, if so desired.

Creating an Ansible script or documentation how we envision the devOps is more valuable than opinionating the executable here.

closing this ticket
