### ISSUE TITLE
suggest to specify --rpcaddr 0.0.0.0 in docker

### ISSUE THREAD

**Issue by benjaminbollen** [OpenST/mosaic-chains#7]
For go-ethereum JSON-RPC to listen on all addresses (specific to running in docker) add option `--rpcaddr 0.0.0.0` to default options; otherwise the RPC server responds with an empty response.  Possibly treat with care.

**Comment by schemar** [comment]
Do you think this is sufficient? c75b9e909439beb973dc1abc4b2a3ea736949b41

**Comment by schemar** [comment]
Done, see https://github.com/OpenST/mosaic-chains/blob/ee00fd73b7efc974d9aa37a048539db43f0af78b/mosaic
