### ISSUE TITLE
Create mosaic chain config object from given path

### ISSUE THREAD

**Issue by deepesh-kn** [OpenST/mosaic-chains#95]
Create `MosaicConfig` object by providing the path of an existing `mosaic-config.json`

**Comment by puneet-khushwani-eth** [comment]
With my changes relating to https://github.com/OpenST/mosaic-chains/issues/98, I had added a method to solve this purpose
 
`MosaicConfig.fromFile`

**Comment by deepesh-kn** [comment]
Closing this issue as its already handled in #98
